platform :ios, '7.0'
use_frameworks!

target 'LittleMonkey' do

pod 'SDWebImage', '~> 3.7.1'
pod 'AFNetworking', '~> 2.6.0'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'LKDBHelper', '~> 2.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'ZBarSDK', '~> 1.3.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'RESideMenu', '~> 4.0.7'
pod 'NSDate+TimeAgo', '~> 1.0.3'
pod 'Masonry'
pod 'DZNEmptyDataSet'
pod 'PureLayout'
pod 'JSPatch'
pod 'FreeStreamer'
pod 'CWStatusBarNotification', '~> 2.3.4'

end
